# Generated by Django 4.0 on 2022-01-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='bootstrap_colour',
            field=models.CharField(default='badge-primary', max_length=20),
        ),
    ]
